/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jorbit_spice_jni_Furnsh */

#ifndef _Included_jorbit_spice_jni_Furnsh
#define _Included_jorbit_spice_jni_Furnsh
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jorbit_spice_jni_Furnsh
 * Method:    cFurnsh
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jorbit_spice_jni_Furnsh_cFurnsh
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
